---
name: Net-Pcap-Easy
version: 1.1
author:
  - 'Paul Miller <paul@cpan.org>'
abstract: "Net::Pcap is awesome, but it's difficult to bootstrap"
license: lgpl
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Net::Netmask: 0
  Net::Pcap: 0
  NetPacket::ARP: 0
  NetPacket::Ethernet: 0
  NetPacket::ICMP: 0
  NetPacket::IP: 0
  NetPacket::TCP: 0
  NetPacket::UDP: 0
  Socket: 0
build_requires:
  File::Slurp: 0
provides:
  Net::Pcap::Easy:
    file: Easy.pm
    version: 1.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
