--- #YAML:1.0
name:                Net-Pcap-Easy
version:             1.32
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::Slurp:                   0
    Net::Netmask:                  0
    Net::Pcap:                     0
    NetPacket::ARP:                0
    NetPacket::Ethernet:           0
    NetPacket::ICMP:               0
    NetPacket::IP:                 0
    NetPacket::TCP:                0
    NetPacket::UDP:                0
    Socket:                        0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
